import './globals.css';
import { Space_Grotesk } from 'next/font/google';
import { Providers } from './providers';

const spaceGrotesk = Space_Grotesk({ 
  subsets: ['latin'],
  weight: ['300', '400', '700'] 
});

export const metadata = {
  title: 'AI Article Generator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 👇 CHANGED: Added "dark" here to force dark mode
    <html lang="en" className="dark" suppressHydrationWarning>
      <body 
        // 👇 CHANGED: Added "bg-slate-950 text-white" so the background is dark immediately
        className={`${spaceGrotesk.className} antialiased bg-slate-950 text-white`}
        suppressHydrationWarning={true}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}